### ISSUE TITLE
Дата/время создания файла на SD не соответстивут текущей дате/времени

### ISSUE THREAD

**Issue by SVRG** [itahoe/gnss_dock#3]
Даты создания файлов лога не соответствуют текущим датам. Например указывается 2023 год.

**Comment by itahoe** [comment]
Проблема возникает только в случае, если время со спутников еще не получено?

Если так, то источник проблемы в том, что модули RTK и DR выдают разные initial time. Поскольку для слияния, в эту ветку переносится код из ветки RTK, значение смещения initial time унаследовано от RTK модуля.

Какие вижу варианта решения:
1. Пока в системе отсутствует корректное время, старт записи не происходит.
2. Пока в системе отсутствует корректное время, старт записи находится в отложенном состоянии.
3. Пока не было первого фикса, в системе время принудительно ставится на 01/01/1970, а время с модулей игнорируется.

**Comment by SVRG** [comment]
В названии файла дата отмечается корректно, что означет наличие времени. Но сама дата создания файла (в свойствах файла) не соответствует действительности.
